name: 'torrentbox'
services:
  torrentbox:
    container_name: torrentbox
    cap_add:
      - NET_ADMIN
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=0
    build:
      context: .
    volumes:
      - ./docker/init.sh:/run/init.sh
      - ./docker/etc/transmission-daemon:/etc/transmission-daemon
    ports:
      - '9091:9091'
    secrets:
      - nordvpn_token

secrets:
  nordvpn_token:
      file: ./.nordvpn_token
