name: 'torrentbox'
services:
  torrentbox:
    container_name: torrentbox
    build:
      context: .
    volumes:
      - ./docker/var/lib/transmission-daemon:/var/lib/transmission-daemon
    ports:
      - '9091:9091'
